language: node_js
env: TRAVIS_CI=true
node_js:
  - '5'
matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

script:
  - npm run coverage:test

after_success:
  - npm run coverage:report
